### ISSUE TITLE
Errors while turning server on with plugin loaded

### ISSUE THREAD

**Issue by ghost** [GamakCZ/EggWars#15]
[Server thread/CRITICAL]: ErrorException: "yaml_parse(): end of stream reached without finding document 0" (EXCEPTION) in "src/pocketmine/utils/Config" at line 155

[Server thread/CRITICAL]: Error: "Call to a member function saveArenas() on null" (EXCEPTION) in "EggWars-master/src/eggwars/EggWars" at line 45

**Comment by GamakCZ** [comment]
I'm working on a repair :)

**Comment by ghost** [comment]
Np, just wanted to let you know

**Comment by ghost** [comment]
Btw @GamakCZ you made a typo there in EggWars file
It's "resources" instead "rescourses"
