### ISSUE TITLE
Problem to join the team

### ISSUE THREAD

**Issue by ghost** [GamakCZ/EggWars#24]
Hello,
I created with the video 2 teams: Red and Black and when I enter the lobby, I can join only one team, the Black team, so the game does not start as all players are in the Black team ...

**Comment by GamakCZ** [comment]
There are two ways to join the team

1) Using vool in inventory
2) Using command /team <teamName>

How do you join the teams?

**Comment by ghost** [comment]
I can join the red team with / team Red but not with the red wool block.

**Comment by GamakCZ** [comment]
Until the error is fixed, you can use &4 instead of &c.
