### ISSUE TITLE
Problem with the shop

### ISSUE THREAD

**Issue by ghost** [GamakCZ/EggWars#30]
The menu of the shop opens well, but I can buy items only (sword, cake, armor) but not items with several items (block, steak ...) Watch the video: https://sendeyo.com/show/f2a27ef14a
The password: 12345678

**Comment by GamakCZ** [comment]
I thik I fixed it. Do you tested it at new version?

**Comment by ghost** [comment]
Yes dev #61

**Comment by ghost** [comment]
I can buy the items but some purchase with several items do not work

**Comment by ghost** [comment]
Block (4 and 32) steak...

**Comment by GamakCZ** [comment]
what items?

**Comment by ghost** [comment]
I will give you an exact list of what works and what does not work

**Comment by GamakCZ** [comment]
come on my server,  I need to reproduce bugs ip play.factionpe.tk port 20000

**Comment by ghost** [comment]
Not work :
Sandstone ×4 and ×32
Apple ×5
Steak ×4
