### ISSUE TITLE
Not working :/

### ISSUE THREAD

**Issue by PixelzChris** [GamakCZ/EggWars#35]
Turanic 1.2.10 there is critical error

https://cdn.discordapp.com/attachments/403876597465350144/417438700759285781/Screenshot_2018-02-25-23-52-00-480_net.fengberd.minecraftpe_server.png
Here is a screenshot

**Comment by GamakCZ** [comment]
Do you use pmmp?

**Comment by PixelzChris** [comment]
Yeah

**Comment by PixelzChris** [comment]
Before the last update it was working... (not very good) but it was working
Btw very good job!

**Comment by PixelzChris** [comment]
Btw my server is not using pmmp but it can load pmmp files (turanic)
Fix it pls

**Comment by GamakCZ** [comment]
Plugin supports only pocketmine (https://pmmp.io)
