### ISSUE TITLE
Paid Job

### ISSUE THREAD

**Issue by PluggedPointers** [GamakCZ/EggWars#37]
I know this isn't the place to write this, but I could not find your contact information. 
Could you please send me some way to privately talk? Rather that be email or social media? 
I own a MCPE server network & have a paid job that needs to be filled, and you fit my requirements.

**Comment by GamakCZ** [comment]
discord VixikCZ#2992

**Comment by PluggedPointers** [comment]
xD I sorry to be a bother, but anything other then discord? I am currently having some problems with it. (It is a long story.)

**Comment by GamakCZ** [comment]
mail gamak.pmmp@gmail.com

**Comment by PluggedPointers** [comment]
TY, I will send you a email rn

**Comment by PluggedPointers** [comment]
I sent both an email and hangouts msg. :D

**Comment by PluggedPointers** [comment]
Hey GamakCZ, are you alive? We need to get the ball rolling. Is hangouts not the best? orrr you just busy?
