### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by ghost** [GamakCZ/EggWars#41]
Hey,

Your plugin is so nice but when i finished the setup, and i would how click on the join sign i doesnt get a message or an teleport :( were use Pocketmine-MP phar from github update list, were have the API3.0.0ALPHA11 an redeactet Version. Please help :D

**Comment by ghost** [comment]
Oh i have wirte my ver false xd
Thats my Version:

Pocketmine-MP 1.7dev-719 REDACTED
API3.0.0ALPHA11 
MCPE Version: MCPE 1.2.10 Bedrock
protocoll version: 201

**Comment by Mastercoding-Entwickler** [comment]
The error is on line 108 and 146 in ShopManager.php you buy alwas two Items but i have op u can bought all Items but the another player can't buy Sandstone. Iff i bought sand stone than i bought this two can you fix this error :c

**Comment by Mastercoding-Entwickler** [comment]
If you death in the Arena and you have Armor this don't clear you have always the Armor in the inventroy can you please fix :3

**Comment by GamakCZ** [comment]
did you enabled the arena?

**Comment by ctw452002** [comment]
Please read Readme. Restart server to fix joinsign

**Comment by ghost** [comment]
Iam enabled the arena, but the signs for the generators doesnt work too. how to set the spawn locations for the teames and how can i set the generator signs?

Please help

**Comment by GamakCZ** [comment]
YouTube video?

2018-03-11 10:47 GMT+01:00 HonorGamerHD <notifications@github.com>:

**Comment by ghost** [comment]
I can make A Video, Presse wait few minutes, sry for my bad english iam from germany XD

**Comment by GamakCZ** [comment]
I was thinked this video 
https://www.youtube.com/watch?v=9wwUFJotC7A&t=2s

**Comment by ghost** [comment]
Oh, i see an video and know i test t setup

**Comment by ejderoyundajb** [comment]
eggwars kit plugins, give me ?


2018-03-13 19:43 GMT+03:00 HonorGamerHD <notifications@github.com>:

**Comment by ghost** [comment]
So, i have do all in your video but when i reload the Server the plugin says theres no arena! But in the eggwars folder there is the world an the arena with all data... i have emabled the arena before the reload and it doesnt works :/

Please help

**Comment by ghost** [comment]
Ive installier the newest dev version, i think it was the dev30 version

**Comment by ghost** [comment]
Oh sry i mean the dev70 build XD

**Comment by GamakCZ** [comment]
What version do you use? (poggit)

**Comment by ResLio** [comment]
iam spamming

**Comment by ghost** [comment]
Now ive use the latest update dev#71 

My pmmp ver:
Pocketmine-MP 1.7dev Redacted
64bit
Php 7.2
MCPE: 1.2.10-1.2.11
Api: 3.0.0 Alpha 11

**Comment by ghost** [comment]
Your newest build (dev#71) cant add worlds :(

**Comment by GamakCZ** [comment]
closed due to removed account
