### ISSUE TITLE
Cant pvp 

### ISSUE THREAD

**Issue by ctw452002** [GamakCZ/EggWars#43]
I have turned on PVP but we still cant pvp in arena

**Comment by ghost** [comment]
I also have this problem :(

**Comment by q1an1x** [comment]
I've fixed that. https://github.com/GamakCZ/EggWars/pull/42/commits/432198b6b0eb70b15d637b6ea73cf963b4f9831b

**Comment by ghost** [comment]
Ok thanks but the generators no longer work which is problematic and we can not change the time of the game and the author of the map (I try by the files but it does not work either)
