### ISSUE TITLE
The plugin isn't working.

### ISSUE THREAD

**Issue by XFIREGANER** [GamakCZ/EggWars#51]
## Issue name

**Issue description**

- ...

**Server software:**

- PocketMine-MP 1.7dev-743 with API 3.0.0-ALPHA11

**Plugin version:**

- 1.0.0-beta1

**Steps to reproduce:**

1) ....
2) ....
3) ....

- [x] Tested without other plugins
- [x] There are not same issue

**Comment by PixelzChris** [comment]
Yeah its not even loading

**Comment by ctw452002** [comment]
it is lol
