### ISSUE TITLE
villager

### ISSUE THREAD

**Issue by ResLio** [GamakCZ/EggWars#52]
## villager spawner

**Issue description**

- villager spawner

**Server software:**

- PocketMine-MP 1.7dev-743 with API 3.0.0-ALPHA11

**Plugin version:**

- 1.0.0-beta1

**villager:**

1)what spawner?
2) villager spawner what command ?

- [x] Tested without other plugins
- [x] There are not same issue

**Comment by ctw452002** [comment]
To open eggwars shop gui do /ew shop. To make villager shop just spawn villager (not slapper/npc). 

NOTE: the command and villager shop ONLY working when the match is running.

**Comment by ResLio** [comment]
the villager does not spawn

**Comment by ctw452002** [comment]
you have to spawn it yourself by the spawn egg in your inv

**Comment by ResLio** [comment]
no I want to lay the villagers

**Comment by ctw452002** [comment]
Create a slapper with ''/slapper create villager (text)'' (to lay villager )  and then add '/slapper edit (id) rca (player) ew shop'

**Comment by ctw452002** [comment]
'/slapper edit (id) addcommand rca (player) ew shop' *

**Comment by GamakCZ** [comment]
use spawn egg

![minecraft 02 04 2018 12_04_14](https://user-images.githubusercontent.com/17053298/38192631-077da5c4-366e-11e8-9c1b-242d41c04b5b.png)
