### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ghost** [GamakCZ/EggWars#53]
The setteam Not working!

**Comment by ctw452002** [comment]
setteam red §c or §4

**Comment by ghost** [comment]
And Others teams

**Comment by ghost** [comment]
Not working!

**Comment by ctw452002** [comment]
well. its working fine for me

**Comment by ghost** [comment]
How? It Come: Usage: setteam color

**Comment by ctw452002** [comment]
copy this  'setteam red §c'  and paste it

**Comment by ctw452002** [comment]
oh my bad... try use "addteam red §c"
