### ISSUE TITLE
Could not enable arena,complete setup first.

### ISSUE THREAD

**Issue by Saxavlax001** [GamakCZ/EggWars#56]
**Issue description**

- I can't enable the eggwars arena I set.I used /ew set arenaname and I did all the things that it needed,then /ew level set arenaname I did all the needed things again but still it says could not enable arena,....

**Server software:**

- PocketMine-MP release 3.7.0 but its not that the problem

**Plugin version:**

- 1.0.0-beta1

**Steps to reproduce:**

1) /ew create arenaname
2) /ew set arenaname
3) /ew level set arenaname

- [ ] Tested without other plugins
- [x] There are not same issue

**Comment by GamakCZ** [comment]
plugin is not done

**Comment by GamakCZ** [comment]
fixed
